### PR TITLE
Support non-transactional databases

### PR DESCRIPTION
**Pull request by MMatten**
Do not attempt to change auto-commit behaviour for non-transactional databases.

This change is required to support Informix databases running in Informix rather than ANSI mode.

### CODE REVIEW

**Comment by javornikolov** [comment]
Looks good to me :+1: 
 - does `Connection.getAutocmmit` return `true` when the database is `Informix` mode (when there is no transaction support)?
 - Does it fail on attempt to execute `setAutocommit(false)`?

**Comment by MMatten** [comment]
> does Connection.getAutocmmit return true when the database is Informix mode (when there is no transaction support)?

Yes. It's the default mode when connecting to an ANSI mode DB too.

>Does it fail on attempt to execute setAutocommit(false)?

Yes. We get an error say "Transactions not supported".

**Comment by MMatten** [comment]
I was thinking of setting the auto-commit option `Options` to `true` too when we detect no transaction support. Any view?

**Comment by javornikolov** [comment]
I wondered about a similar question: what if we have auto-commit = `auto`?

**Comment by MMatten** [comment]
> I wondered about a similar question: what if we have auto-commit = `auto`?

Can you remind me what that does? What happens in `Options` method `public static boolean is(String option)` when the option value is `auto`?

**Comment by javornikolov** [comment]
`is("auto")` will return `false`. Currently we use `Options.get(OPTION_AUTO_COMMIT)` to test for `auto`. The `auto` mode leaves the JDBC driver defaults - it doesn't invoke `setAutoCommit`.

**Comment by javornikolov** [comment]
Anyway - I think the current version looks good enough for now. I'm merging it.

**Pull request merged**
