### PR TITLE
Bump up gradle to 3.3

### PR DESCRIPTION
**Pull request by javornikolov**

### CODE REVIEW

**Comment by MMatten** [comment]
Happy new year to you! Any testing I can help with?

**Comment by javornikolov** [comment]
Hi @MMatten, Thank you! Happy New Year to you too :-)
The build failed due to some intermittent issue for no apparent reasons when pulling dependencies on CI. I just triggered a rebuild which succeeded so I guess all should be fine.

**Comment by MMatten** [comment]
I guess there's no need to run an `integrationBuild` task to test these Gradle updates as we have MySQL tests running in the CI.

**Comment by javornikolov** [comment]
> I guess there's no need to run an integrationBuild task to test these Gradle updates as we have MySQL tests running in the CI.

Yes, it's same build steps for all adapters so no need to run them all.

**Pull request merged**
