### PR TITLE
Add build dependencies for forthcoming Informix adapter to AWS Ivy repo

### PR DESCRIPTION
**Pull request by MMatten**
Upload of Informix dependency for forthcoming Informix adapter.

This is required for setting up the acceptance test database objects using `dbdeploy` as the `custom_libs` repository does not seem to be searched (but does for compilation and other tasks).

### CODE REVIEW

**Comment by MMatten** [comment]
In fact I can only see the resource `https://s3.amazonaws.com/dbfit/ifxjdbc-3.70.jar` being requested (not even Maven central or mvnrepository).

**Comment by javornikolov** [comment]
On their web site (https://www-01.ibm.com/marketing/iwm/tnd/search.jsp?go=y&rs=ifxjdbc) I can see version `4.10.JC5DE`. Can we use it, isn't it newer version than ifxjdbc-4.10.JC4W1?

**Comment by MMatten** [comment]
`4.10.JC4W1` is the version that comes with the Informix developer edition download.

I've just downloaded `4.10.JC5DE` and file is *exactly* the same as the one I've uploaded. I guess they've just bumped the version number without changing the content.

We can name the file on AWS `ifxjdbc-4.10.JC5DE.jar`.

**Comment by javornikolov** [comment]
Shouldn't we have digits only in the version number (I'm not sure)?

**Comment by MMatten** [comment]
I guess it should have enough in the version string to distinguish it and identify the actual version. 

The Maven naming docs suggest anything goes:

https://maven.apache.org/guides/mini/guide-naming-conventions.html

**Comment by javornikolov** [comment]
I uploaded it as `ifxjdbc-4.10.JC4W1.jar`.

**Comment by MMatten** [comment]
Thanks. What do you suggest we do with this PR / what's good practice? Close it or merge it and delete the file?

**Comment by javornikolov** [comment]
I think it's best to close it and drop the branch. We don't want fat binaries in the code repository.

**Pull request closed without merging**
