### PR TITLE
Release 3.2.0

### PR DESCRIPTION
**Pull request by javornikolov**
## Release date: 15 August 2015

This release adds various small enhancements and bug fixes. A notable enhancement is that starting with version 3.2.0, we're going to publish dbfit artifacts also to [Maven Central Repository](http://search.maven.org/).

Thanks to all contributors and to everyone who reported issues and provided feedback about DbFit!
Special thanks to [Mark Matten](https://github.com/MMatten) who contributed most of the changes!

### New features

* Support long Teradata object names ([#402](https://github.com/dbfit/dbfit/pull/402))
* `bigint unsigned` support for mysql ([#395](https://github.com/dbfit/dbfit/pull/395))
* Auto-commit configuration support ([#385](https://github.com/dbfit/dbfit/pull/385))
* MS SQL Server: Support access to DB objects in connection's non default DB ([#376](https://github.com/dbfit/dbfit/pull/376))
* Support dollar characters in SQL Server object names ([#374](https://github.com/dbfit/dbfit/pull/374))
* HSQLDB: allow mixed case table names in Insert/Update/Clean ([#356](https://github.com/dbfit/dbfit/pull/356))
* mssql stored procedure implicit return value support ([#352](https://github.com/dbfit/dbfit/pull/352))
* Add support for Oracle nested tables and varrays as stored procedures arguments ([#347](https://github.com/dbfit/dbfit/pull/347)) - thanks to @avskor
* Update FitNesse to 20150424 ([#364](https://github.com/dbfit/dbfit/pull/364))
* Publish dbfit jars to Maven Central ([#384](https://github.com/dbfit/dbfit/pull/384))

### Bug fixes

* bump up mysql jdbc to 5.1.36 resolving NumberFormatException issue ([#408](https://github.com/dbfit/dbfit/pull/408))
* Fix support for BIGINT in SPL params ([#389](https://github.com/dbfit/dbfit/pull/389))
* Support case sensitive collation object names in SQL Server ([#362](https://github.com/dbfit/dbfit/pull/362))
* fix mssql proc params metadata query errors ([#353](https://github.com/dbfit/dbfit/pull/353))

### Documentation improvements

* Add instructions for remote debugging with Eclipse ([#378](https://github.com/dbfit/dbfit/pull/378))
* integrated windows authentication setup instructions ([#344](https://github.com/dbfit/dbfit/pull/344)) - thanks to [Daniel Maresma](https://github.com/Auguronomics)

### Development and Project improvements

* Internal tests refactoring and improvements
* Ability to control which integration tests to run
* Test VM base box update, 8085 port forwarding, other maintenance
* Gradle updated to latest version
* Others

--
Full list of changes is available [here](https://github.com/dbfit/dbfit/pulls?utf8=%E2%9C%93&q=milestone%3A3.2.0)

### CODE REVIEW

**Comment by MMatten** [comment]
Regarding including any other additional changes: -
* there was a request on the Google forum to change the Netezza parameter prefix to `:` from `_:`.
* in #406 we identified a potential new feature - setting the parameter prefix character/string via a new `Set Option` option.

These two can probably be dealt with fairly quickly.
Also, #407 sounds like an interesting piece.

There's tons of other issues to look too of course. Perhaps we can push out a new version every 2-3 months in the future, or patch releases for bug fixes as they get resolved.

Anything else you think we really should get into `3.2.0`?

**Comment by MMatten** [comment]
What about pushing out 3.2.0 now and scoping out the next couple of releases straight after? I think a statement of direction for the user community would be good too.

**Comment by javornikolov** [comment]
I think we can release what we already have, just we need to prepare the release notes. @benilovj, any concerns?

(As per the pending issues/enhancements: we can release as often as we have something new which is useful for the audience).

**Comment by benilovj** [comment]
I personally think it's worth releasing whenever any kind of external improvement (new feature or bugfix) has been merged, as often as possible. Ideally the release process should be as simple as adding changenotes and bumping the version - everything else (doc generation, website rebuild, release artefact) should really be automated. Anecdotally, releasing often seems to make the community more engaged and lead to more external contributions. 

So basically :shipit: :)

**Comment by MMatten** [comment]
@benilovj - can you consider getting out anything like a roadmap or statement of direction for the project too along with this release (or soon)? There was talk of SLIM, Robot, other frameworks and ETL tool utilities and more way back but things have slowed right down since the `3.1.0` release.

**Comment by benilovj** [comment]
@MMatten - as you've noticed, I've taken a step back from this project in the last year (these days, my focus is exclusively on web development and I have very little to do with databases); @javornikolov has been leading efforts since even from before I stepped back.

I tend to think that open source projects live and die by the enthusiasm (or lack of) of the core committers, so the roadmap should be come from the work that the people actually putting the time in (and in the past year that's been @javornikolov and yourself) want to do. My instincts suggest that building DBSlim would allow this project to capitalise on the ongoing development of Fitnesse and bring it to a wider audience, but ultimately the direction is for @javornikolov and yourself to decide.

**Comment by javornikolov** [comment]
Yes, things slowed down lately; I've been having less time to devote to the project, mostly adhoc involvement during some of the weekends, focusing on sustaining the existing functionality/supporting users's requests for help. Thank you @MMatten for holding on the front!

Trying out Slim is something I'd also vote for. It needs some research/experimentation to see if that's feasible, how can be done, etc.

Other directions might be adding support for new databases, and improving the support for existing ones (special features which we don't yet support).

It's also good to tidy up the existing backlog of issues & pull requests (see what we can easily close).

--
Exact scoping of future releases (even next few ones) is maybe an overkill. But we can somehow mark what's *under the radar* - e.g. in Github via milestones or labels; or in Trello or some other way.

Let's attempt to release a new functionality as soon as we have it (e.g. at the end of the week when it was merged to master). I'm planning to push out 3.2.0 release today or tomorrow.

**Comment by MMatten** [comment]
It might also be good to ask the Google and Yahoo forums for input on future direction. I agree about SLIM too. Then there's loads of new non relational DB types that might be worth looking at supporting where that's sensible.

@benilovj - thanks for the update. I hope you can still pop in from time to time. 

@javornikolov - I guess we will end up with rapidly increasing version numbers if we release on every feature/enhancement and I'd agree with @benilovj about frequent releases and community engagement (with the addition of perhaps periodically publishing some news about where the project is going and what's being worked on etc).

Good news to see a new release is about to happen :smile:.

**Pull request merged**
