### PR TITLE
Bump Gradle 6.5.1 and Java 1.8

### PR DESCRIPTION
**Pull request by bhuesemann**
Contains:
- Gradle update 6.5.1 (numerous changes in build.gradle to the new configuration separation syntax)
- Java update >= 1.8 (needed for gradlew)
- Mockito bump due to deprecation warnings jdk8
- Oracle changes due to deprecation warnings jdk8
- Gradle plugin 'java' to 'java-library' due to easier dependency management

These changes are closely related and are not easy to separate.

### CODE REVIEW

**Comment by javornikolov** [comment]
Can we bump up java compatibility in separate PR? I think grade upgrade is not so significant compared to JDK change. If things are too tightly tied up - at least change PR title.

**Comment by bhuesemann** [comment]
Gradle bump requires JDK 8 so things can't be separated easy. I started with the aim to bump gradle only but ended up with upgrading java, too. All the code changes related to fixing warnings with usage of unqualified generics are not included and will go in a separate PR.

**Comment by javornikolov** [comment]
What about having PR for Java only without gradle?

**Comment by bhuesemann** [comment]
#654 I don't feel like I've invested my evening on something really valuable here.

**Comment by bhuesemann** [comment]
This PR is obsolete now and replaced by #654. @javornikolov

**Pull request closed without merging**
