### PR TITLE
Update to SQL Server installer

### PR DESCRIPTION
**Pull request by MMatten**
Update installer to re-align with Microsoft config utility options.

### CODE REVIEW

**Comment by javornikolov** [comment]
Do we want to merge that before the release? If that's the case - can we remove the d13c281 commit from here since it's not merged yet to master.

**Comment by MMatten** [comment]
> Do we want to merge that before the release? If that's the case - can we remove the d13c281 commit from here since it's not merged yet to master.

Right. I'd just spotted that. Let me fix this.

**Comment by MMatten** [comment]
@javornikolov Fixed.

**Comment by javornikolov** [comment]
Thank you, @MMatten! I guess it works fine so I'm merging it and I'll rebase the release branch after that.

**Pull request merged**
