### PR TITLE
Fix SQL Server case sensitive collation issues - phase 1 - disable broken tests

### PR DESCRIPTION
**Pull request by MMatten**
PR1 - park broken SQL Server tests.

The tests are broken because the feature hasn't been implemented in Java. E.g. SQL Variant in StringTest and Binary data types

### CODE REVIEW

**Comment by MMatten** [comment]
Start of resolving #348.

**Comment by javornikolov** [comment]
Are the tests broken due to the case-sensitivity issue or for other reason?

Now I realized that when I suggested separate PRs in #348 I imagined we'll be moving tests which are broken in general (not due to case-sensitivity).

**Comment by MMatten** [comment]
These tests, that I've moved, are broken because the feature hasn't been implemented in Java.

**Comment by javornikolov** [comment]
OK, then it's good that we have that in separate PR. I'll change the PR title a bit and I'm merging.

**Pull request merged**
