### PR TITLE
Bump up FitNesse version to 20220319

### PR DESCRIPTION
**Pull request by MMatten**
Bump up FitNesse to version 20220319.

Tasks - test with:
- [x] DB2
- [x] Derby
- [x] HSQLDB
- [x] Informix
- [x] MySQL
- [x] Netezza
- [x] Oracle
- [x] PostgreSQL
- [ ] Snowflake
- [x] SQL Server
- [x] Teradata

### CODE REVIEW

**Comment by MMatten** [comment]
@javornikolov I'm hoping that the CI build can cover much of the testing for this (seeing as the test VM provisioning is broken again). I've noticed there is no Java 11 SQL Server. Do you know what that is?

I'll look to test the other adapters over the next week or two.

**Comment by javornikolov** [comment]
> @javornikolov I'm hoping that the CI build can cover much of the testing for this (seeing as the test VM provisioning is broken again). I've noticed there is no Java 11 SQL Server. Do you know what that is?
> 
> I'll look to test the other adapters over the next week or two.

Thanks, @MMatten, seems I have forgotten to add Java 11 for sqlserver - it's defined in .github/workflows/build.yml

**Comment by MMatten** [comment]
@javornikolov I think I've tested all that I can so I think this is ready to merge.

There seem to be problems with the Snowflake code that introducing the `CoreTests` suite is bringing out so I'll look to address this via another PR. Are we ok to merge this one?

**Comment by javornikolov** [comment]
@MMatten, thanks! Yes, the fitnesse update itself seems OK, I am merging.

**Pull request merged**
