### PR TITLE
Fix failing Netezza symbols core tests

### LINKED ISSUE #578: Fix failing CoreTests for Netezza
Related to #565 

Requires new unified `CalcLength` stored routine, etc.

### PR DESCRIPTION
**Pull request by javornikolov**
Resolves #578 

* Parameterize CalcLength parameters in Symbols acceptance tests  
* Create CalcLength stored procedure for Netezza
* Implement support for Neteza functions return values

* Fix a small old typo in 001_add_objects_needed_for_acceptance_test.sql

### CODE REVIEW

**Comment by javornikolov** [comment]
@MMatten, I hope that should solve the Netezza tests failure. Possibly we may need to also rename the input parameter (e.g. to `$1`) but I'm not quite sure yet.
Would you be able to test it?

**Comment by javornikolov** [comment]
> Possibly we may need to also rename the input parameter (e.g. to $1) but I'm not quite sure yet.

Pretty much looks like we should follow the $n naming so I just changed and force pushed it that way.

**Comment by MMatten** [comment]
I'm getting a failure in `CoreTests.CommonSuite.Symbols` whilst executing `CalcLength`: -

```
java.sql.SQLException: Cannot find parameter ""
	at dbfit.api.DbStoredProcedure.findAccessorForParamWithName(DbStoredProcedure.java:42)
	at dbfit.api.DbStoredProcedure.getDbParameterAccessor(DbStoredProcedure.java:29)
	at dbfit.fixture.DbObjectExecutionFixture.getAccessors(DbObjectExecutionFixture.java:121)
	at dbfit.fixture.DbObjectExecutionFixture.getAccessors(DbObjectExecutionFixture.java:108)
	at dbfit.fixture.DbObjectExecutionFixture.doRows(DbObjectExecutionFixture.java:71)
	at fit.Fixture.doTable(Fixture.java:156)
	at fitlibrary.traverse.AlienTraverseHandler.doTable(AlienTraverseHandler.java:21)
	at fitlibrary.traverse.workflow.DoTraverseInterpreter.interpretWholeTable(DoTraverseInterpreter.java:104)
	at fitlibrary.traverse.workflow.DoTraverseInterpreter.interpretWholeTable(DoTraverseInterpreter.java:89)
	at fitlibrary.DoFixture.interpretWholeTable(DoFixture.java:73)
	at fitlibrary.suite.InFlowPageRunner.run(InFlowPageRunner.java:27)
	at fitlibrary.DoFixture.interpretTables(DoFixture.java:42)
	at dbfit.DatabaseTest.interpretTables(DatabaseTest.java:26)
	at fit.Fixture.doTables(Fixture.java:81)
	at fit.FitServer.process(FitServer.java:81)
	at fit.FitServer.run(FitServer.java:56)
	at fit.FitServer.main(FitServer.java:41)
```

**Comment by MMatten** [comment]
Note that in the `_v_procedure` system view this another column called `RETURNS`. It specifies the data type of the `RETURNS` clause for a procedure. 

Perhaps we can use this to return the `OUT` param via the SQL query.

**Comment by javornikolov** [comment]
Indeed - Netezza dbfit environment  doesn't support return values yet. Perhaps RETURNS column is what we need to form the return value descriptor.

**Comment by MMatten** [comment]
@javornikolov let me know if you need me to run any SQL queries, tests, etc, etc.

**Comment by javornikolov** [comment]
@MMatten, I just pushed an attempt to add Netezza function return value support. May we test with it please.  (It might worth adding some specific acceptance test for that but for a start we may use the Symbols tests).

**Comment by MMatten** [comment]
I got a build error: -

```
:dbfit-java:netezza:compileJava
/var/dbfit/dbfit-java/netezza/src/main/java/dbfit/environment/NetezzaEnvironment.java:258: error: variable paramName might not have been initialized
            allParams.put(NameNormaliser.normaliseName(paramName), dbp);
                                                       ^
1 error
:dbfit-java:netezza:compileJava FAILED

FAILURE: Build failed with an exception.
```

**Comment by javornikolov** [comment]
Yes, sorry, I saw that too. I just force-pushed a version which should compile OK.

**Comment by MMatten** [comment]
In `FlowMode.CallProcedures` I get the error: -

```
org.netezza.error.NzSQLException: Column Index out of range: 2
	at org.netezza.sql.NzResultSet.getPgString(NzResultSet.java:2806)
	at org.netezza.sql.NzResultSet.getString(NzResultSet.java:1378)
	at dbfit.environment.NetezzaEnvironment.getAllProcedureParameters(NetezzaEnvironment.java:220)
	at dbfit.fixture.Inspect.inspectProcedure(Inspect.java:70)
	at dbfit.fixture.Inspect.doTable(Inspect.java:44)
	at fitlibrary.traverse.AlienTraverseHandler.doTable(AlienTraverseHandler.java:21)
	at fitlibrary.traverse.workflow.DoTraverseInterpreter.interpretWholeTable(DoTraverseInterpreter.java:104)
	at fitlibrary.traverse.workflow.DoTraverseInterpreter.interpretWholeTable(DoTraverseInterpreter.java:89)
	at fitlibrary.DoFixture.interpretWholeTable(DoFixture.java:73)
	at fitlibrary.suite.InFlowPageRunner.run(InFlowPageRunner.java:27)
	at fitlibrary.DoFixture.interpretTables(DoFixture.java:42)
	at dbfit.DatabaseTest.interpretTables(DatabaseTest.java:26)
	at fit.Fixture.doTables(Fixture.java:81)
	at fit.FitServer.process(FitServer.java:81)
	at fit.FitServer.run(FitServer.java:56)
	at fit.FitServer.main(FitServer.java:41)
```

**Comment by MMatten** [comment]
Executing `CalcLength` I get: -

```
org.netezza.error.NzSQLException: Column Index out of range: 2
	at org.netezza.sql.NzResultSet.getPgString(NzResultSet.java:2806)
	at org.netezza.sql.NzResultSet.getString(NzResultSet.java:1378)
	at dbfit.environment.NetezzaEnvironment.getAllProcedureParameters(NetezzaEnvironment.java:220)
	at dbfit.api.DbStoredProcedure.getAllParams(DbStoredProcedure.java:49)
	at dbfit.api.DbStoredProcedure.findAccessorForParamWithName(DbStoredProcedure.java:40)
	at dbfit.api.DbStoredProcedure.getDbParameterAccessor(DbStoredProcedure.java:29)
	at dbfit.fixture.DbObjectExecutionFixture.getAccessors(DbObjectExecutionFixture.java:121)
	at dbfit.fixture.DbObjectExecutionFixture.getAccessors(DbObjectExecutionFixture.java:108)
	at dbfit.fixture.DbObjectExecutionFixture.doRows(DbObjectExecutionFixture.java:71)
	at fit.Fixture.doTable(Fixture.java:156)
	at fitlibrary.traverse.AlienTraverseHandler.doTable(AlienTraverseHandler.java:21)
	at fitlibrary.traverse.workflow.DoTraverseInterpreter.interpretWholeTable(DoTraverseInterpreter.java:104)
	at fitlibrary.traverse.workflow.DoTraverseInterpreter.interpretWholeTable(DoTraverseInterpreter.java:89)
	at fitlibrary.DoFixture.interpretWholeTable(DoFixture.java:73)
	at fitlibrary.suite.InFlowPageRunner.run(InFlowPageRunner.java:27)
	at fitlibrary.DoFixture.interpretTables(DoFixture.java:42)
	at dbfit.DatabaseTest.interpretTables(DatabaseTest.java:26)
	at fit.Fixture.doTables(Fixture.java:81)
	at fit.FitServer.process(FitServer.java:81)
	at fit.FitServer.run(FitServer.java:56)
	at fit.FitServer.main(FitServer.java:41)
```

**Comment by javornikolov** [comment]
That was because I forgot to add `retuns` column to the SQL query... Fixed now.

**Comment by MMatten** [comment]
`FlowMode.CallProcedures` is now passing.

`CoreTests.CommonSuite.Symbols` now fails with: -

```
org.netezza.sql.NzCallableStatement$OutParameterNorRegisteredException: out parameter not registered
	at org.netezza.sql.NzCallableStatement.getObject(NzCallableStatement.java:684)
	at dbfit.fixture.StatementExecution.getObject(StatementExecution.java:31)
	at dbfit.util.DbParameterAccessor.get(DbParameterAccessor.java:118)
	at dbfit.util.DbParameterAccessorTypeAdapter.get(DbParameterAccessorTypeAdapter.java:18)
	at dbfit.util.SymbolAccessQueryBinding.doCell(SymbolAccessQueryBinding.java:15)
	at dbfit.fixture.DbObjectExecutionFixture.executeStatementAndEvaluateOutputs(DbObjectExecutionFixture.java:188)
	at dbfit.fixture.DbObjectExecutionFixture.runRow(DbObjectExecutionFixture.java:155)
	at dbfit.fixture.DbObjectExecutionFixture.doRows(DbObjectExecutionFixture.java:79)
	at fit.Fixture.doTable(Fixture.java:156)
	at fitlibrary.traverse.AlienTraverseHandler.doTable(AlienTraverseHandler.java:21)
	at fitlibrary.traverse.workflow.DoTraverseInterpreter.interpretWholeTable(DoTraverseInterpreter.java:104)
	at fitlibrary.traverse.workflow.DoTraverseInterpreter.interpretWholeTable(DoTraverseInterpreter.java:89)
	at fitlibrary.DoFixture.interpretWholeTable(DoFixture.java:73)
	at fitlibrary.suite.InFlowPageRunner.run(InFlowPageRunner.java:27)
	at fitlibrary.DoFixture.interpretTables(DoFixture.java:42)
	at dbfit.DatabaseTest.interpretTables(DatabaseTest.java:26)
	at fit.Fixture.doTables(Fixture.java:81)
	at fit.FitServer.process(FitServer.java:81)
	at fit.FitServer.run(FitServer.java:56)
	at fit.FitServer.main(FitServer.java:41)
```

**Comment by javornikolov** [comment]
Hmm... I just added in FlowMode.CallProcedures another test for sp_procedure return value and Inspect Procedure and direct calls to CalcLength.

**Comment by javornikolov** [comment]
Gee, looks like we're already in debt with that: https://www.ibm.com/developerworks/community/forums/html/threadTopic?id=6ab238ce-f4d2-48f9-ae4e-f9e648fff9fe

**Comment by MMatten** [comment]
> Gee, looks like we're already in debt with that (#11): https://www.ibm.com/developerworks/community/forums/html/threadTopic?id=6ab238ce-f4d2-48f9-ae4e-f9e648fff9fe

No, no out params in stored procs and no function return values? 

May be the what we created for Informix would suit this.

Let me test your updates now.

**Comment by javornikolov** [comment]
I decompiled the JDBC driver to see what's going on inside. Looks like it has some support for return values but not through `getObject` but using `getInt`, `getString`, etc... (Internally these are implemented via `getResultSet`). Besides `getBigDecimal` looks a bit buggy at first glimpse.

I'm just working on a `getObject` override to see if we can trick it in that way. I'll push it in a few minutes. Later we may try the `getResultSet` approach too.

**Comment by javornikolov** [comment]
@MMatten, I just pushed the patched Netezza environment.

**Comment by MMatten** [comment]
`CallProcedures` fails with: -

image

**Comment by javornikolov** [comment]
> Everything else seems to be passing.

Great :-)
I fixed the other part too (I didn't pay attention that the function call had side effect in populating a table).

**Comment by javornikolov** [comment]
At first glimpse the Informix approach for function calls should work here out of the box. I'll change that shortly to see if we can get rid of my getObject overrides.

**Comment by javornikolov** [comment]
> At first glimpse the Informix approach for function calls should work here out of the box. I'll change that shortly to see if we can get rid of my getObject overrides.

Done - pushed with 4bee54e.

**Comment by MMatten** [comment]
In `CallProcedures` where we're testing procs and looking for the output I'm getting: -

```
org.netezza.error.NzSQLException: Value can be set for IN/INOUT parameter type only
	at org.netezza.sql.NzCallableStatement.setObject(NzCallableStatement.java:2031)
	at dbfit.fixture.StatementExecution.setObject(StatementExecution.java:26)
	at dbfit.fixture.StatementExecutionCapturingResultSetValue.setObject(StatementExecutionCapturingResultSetValue.java:32)
	at dbfit.util.DbParameterAccessor.set(DbParameterAccessor.java:110)
	at dbfit.util.DbParameterAccessorTypeAdapter.set(DbParameterAccessorTypeAdapter.java:22)
	at fit.Binding$SetBinding.doCell(Binding.java:217)
	at dbfit.util.SymbolAccessSetBinding.doCell(SymbolAccessSetBinding.java:22)
	at dbfit.fixture.DbObjectExecutionFixture.runRow(DbObjectExecutionFixture.java:151)
	at dbfit.fixture.DbObjectExecutionFixture.doRows(DbObjectExecutionFixture.java:79)
	at fit.Fixture.doTable(Fixture.java:156)
	at fitlibrary.traverse.AlienTraverseHandler.doTable(AlienTraverseHandler.java:21)
	at fitlibrary.traverse.workflow.DoTraverseInterpreter.interpretWholeTable(DoTraverseInterpreter.java:104)
	at fitlibrary.traverse.workflow.DoTraverseInterpreter.interpretWholeTable(DoTraverseInterpreter.java:89)
	at fitlibrary.DoFixture.interpretWholeTable(DoFixture.java:73)
	at fitlibrary.suite.InFlowPageRunner.run(InFlowPageRunner.java:27)
	at fitlibrary.DoFixture.interpretTables(DoFixture.java:42)
	at dbfit.DatabaseTest.interpretTables(DatabaseTest.java:26)
	at fit.Fixture.doTables(Fixture.java:81)
	at fit.FitServer.process(FitServer.java:81)
	at fit.FitServer.run(FitServer.java:56)
	at fit.FitServer.main(FitServer.java:41)
```

**Comment by MMatten** [comment]
image
I'm still seeing this.

**Comment by javornikolov** [comment]
> I'm still seeing this.

My bad. I moved more calls than needed. should be OK now.

> org.netezza.error.NzSQLException: Value can be set for IN/INOUT parameter type only

Perhaps we sholdn't adjust the parameter index as we do for Informix. I changed that. Let's see if that helps.

**Comment by MMatten** [comment]
Awesome. A clean bill of health again. No test failures.

**Comment by javornikolov** [comment]
Nice :-) I need to tidy up some bits here but looks like that we finally managed to get Netezza functions working.

**Comment by MMatten** [comment]
Great work! 

Interestingly there are also functions in Netezza in addition to stored procs that return values. I think they have to be built in C++ and compiled into the DB. One for another day!

**Comment by javornikolov** [comment]
@MMatten, I did some refactoring. Can we test it again?
And if it looks good enough to you - I think we can merge it (maybe slicing the last commit with the refactoring into a separate PR).

**Comment by MMatten** [comment]
We're still missing the `CalcLength` stored routine for SQL Server.

But I'll test all the others (I just have Teradata to do).

**Comment by MMatten** [comment]
I'm now seeing Netezza failures in `FlowMode.CallProcedures`: -

image

**Comment by javornikolov** [comment]
@MMatten, could you test that again. I hope we have that error fixed now.

**Comment by MMatten** [comment]
All tests are passing now.

**Comment by javornikolov** [comment]
Wonderful :-) Thanks for verifying, @MMatten! I guess we're ready to merge that PR?

**Comment by MMatten** [comment]
Yes. I think so. I've nothing else to add.

**Pull request merged**
