### PR TITLE
Update cookbook versions

### PR DESCRIPTION
**Pull request by javornikolov**
* mysql ~> 8.2. Previously we used to restrict the version < 8.0 due to issues in v8.0. It's supposed not to have such issues with 8.2
* mysql2 chef gem version 0.4.5
* postgresql 5.1
* a few other minor updates

TODO:
- [x] Verify that all works fine after this change.

### CODE REVIEW

**Comment by MMatten** [comment]
Are you able to test this or do you need me?

**Comment by javornikolov** [comment]
@MMatten, could you please test it since my cloud vm trial period has expired. Thank you!

**Comment by MMatten** [comment]
It's still looking ill: -

```
==> default:       ================================================================================
==> default:       Error executing action `create` on resource 'mysql_client_installation_package[default]'
==> default:       ================================================================================
==> default:       
==> default:       Chef::Exceptions::Package
==> default:       -------------------------
==> default:       yum_package[mysql-community-client] (/var/chef/cache/cookbooks/mysql/libraries/mysql_client_installation_package.rb line 18) had an error: Chef::Exceptions::Package: No candidate version available for mysql-community-client
==> default:       
==> default:       Cookbook Trace:
==> default:       ---------------
==> default:       /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
==> default:       /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
==> default:       /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
==> default:       /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
==> default:       /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
==> default:       /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
==> default:       /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
==> default:       /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
==> default:       /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
==> default:       /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
==> default:       /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
==> default:       /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
==> default:       /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
==> default:       /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
==> default:       /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
==> default:       
==> default:       Resource Declaration:
==> default:       ---------------------
==> default:       # In /var/chef/cache/cookbooks/mysql2_chef_gem/libraries/provider_mysql2_chef_gem_mysql.rb
==> default:       
==> default:        16:           mysql_client 'default' do
==> default:        17:             version new_resource.client_version
==> default:        18:             action :create
==> default:        19:           end
==> default:        20: 
==> default:       
==> default:       Compiled Resource:
==> default:       ------------------
==> default:       # Declared in /var/chef/cache/cookbooks/mysql2_chef_gem/libraries/provider_mysql2_chef_gem_mysql.rb:16:in `block in <class:Mysql>'
==> default:       
==> default:       mysql_client_installation_package("default") do
==> default:         action [:create]
==> default:         retries 0
==> default:         retry_delay 2
==> default:         default_guard_interpreter :default
==> default:         declared_type :mysql_client
==> default:         cookbook_name "dbfit_test"
==> default:         version "5.7"
==> default:         major_version "5.7"
==> default:         package_name "mysql-community-client"
==> default:       end
==> default:       
==> default:       Platform:
==> default:       ---------
==> default:       x86_64-linux
==> default:       
==> default: [2016-11-08T20:39:34+00:00] INFO: Running queued delayed notifications before re-raising exception
==> default:     
==> default:     ================================================================================
==> default:     Error executing action `install` on resource 'mysql2_chef_gem[default]'
==> default:     ================================================================================
==> default:     
==> default:     Chef::Exceptions::Package
==> default:     -------------------------
==> default:     mysql_client_installation_package[default] (/var/chef/cache/cookbooks/mysql2_chef_gem/libraries/provider_mysql2_chef_gem_mysql.rb line 16) had an error: Chef::Exceptions::Package: yum_package[mysql-community-client] (/var/chef/cache/cookbooks/mysql/libraries/mysql_client_installation_package.rb line 18) had an error: Chef::Exceptions::Package: No candidate version available for mysql-community-client
==> default:     
==> default:     Cookbook Trace:
==> default:     ---------------
==> default:     /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
==> default:     /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
==> default:     /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
==> default:     /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
==> default:     /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
==> default:     /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
==> default:     /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
==> default:     /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
==> default:     /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
==> default:     /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
==> default:     /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
==> default:     /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
==> default:     /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
==> default:     /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
==> default:     /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
==> default:     
==> default:     Resource Declaration:
==> default:     ---------------------
==> default:     # In /var/chef/cache/cookbooks/dbfit_test/recipes/mysql.rb
==> default:     
==> default:       1: mysql2_chef_gem 'default' do
==> default:       2:   gem_version '0.4.4'
==> default:       3:   client_version node['mysql']['version'] if node['mysql']
==> default:       4:   action :install
==> default:       5: end
==> default:       6: 
==> default:     
==> default:     Compiled Resource:
==> default:     ------------------
==> default:     # Declared in /var/chef/cache/cookbooks/dbfit_test/recipes/mysql.rb:1:in `from_file'
==> default:     
==> default:     mysql2_chef_gem("default") do
==> default:       action [:install]
==> default:       retries 0
==> default:       retry_delay 2
==> default:       default_guard_interpreter :default
==> default:       declared_type :mysql2_chef_gem
==> default:       cookbook_name "dbfit_test"
==> default:       recipe_name "mysql"
==> default:       gem_version "0.4.4"
==> default:       client_version "5.7"
==> default:     end
==> default:     
==> default:     Platform:
==> default:     ---------
==> default:     x86_64-linux
==> default:     
==> default: [2016-11-08T20:39:34+00:00] INFO: Running queued delayed notifications before re-raising exception
==> default: 
==> default: Running handlers:
==> default: [2016-11-08T20:39:34+00:00] ERROR: Running exception handlers
==> default: Running handlers complete
==> default: [2016-11-08T20:39:34+00:00] ERROR: Exception handlers complete
==> default: Chef Client failed. 34 resources updated in 06 minutes 06 seconds
==> default: [2016-11-08T20:39:34+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2016-11-08T20:39:34+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
==> default: [2016-11-08T20:39:34+00:00] ERROR: mysql2_chef_gem[default] (dbfit_test::mysql line 1) had an error: Chef::Exceptions::Package: mysql_client_installation_package[default] (/var/chef/cache/cookbooks/mysql2_chef_gem/libraries/provider_mysql2_chef_gem_mysql.rb line 16) had an error: Chef::Exceptions::Package: yum_package[mysql-community-client] (/var/chef/cache/cookbooks/mysql/libraries/mysql_client_installation_package.rb line 18) had an error: Chef::Exceptions::Package: No candidate version available for mysql-community-client
==> default: [2016-11-08T20:39:34+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```

**Comment by javornikolov** [comment]
I force-pushed an updated version - the need of explicit management of `yum-mysql-community` is retained in `8.1`. Let's try it now.

**Comment by MMatten** [comment]
I can retest this. I take it this need rebasing?

**Comment by javornikolov** [comment]
You can rebase or merge with master locally. Also today I force-pushed here with re-generated `Berkfile.lock` (`compat_resource (12.16.2)` got updated) - so please pick the latest version of the branch here.

**Comment by javornikolov** [comment]
Actually I just rebased on top of master to keep things simpler.

**Comment by MMatten** [comment]
It's still not well.

https://gist.github.com/MMatten/80adc12bc3ebe4584b2ac53c78f78324

**Comment by MMatten** [comment]
Contents of mfmk.log: -

https://gist.github.com/MMatten/a48cef1ba5cf77c348047da6c05c07f1

**Comment by javornikolov** [comment]
Looks like the last errors are due to mysql devel package not being installed.

Perhaps that will be resolved in mysql cookbook as commented at https://github.com/sinfomicien/mysql2_chef_gem/issues/3#issuecomment-257372997 - so let's wait for that.

**Comment by javornikolov** [comment]
@MMatten, I just pushed an update to pick mysql 8.2 cookbook which is supposed to resolve the pending issues here. Would you be able to test it?

**Comment by MMatten** [comment]
I've just built a brand new VM from this. 

`vagrant up` and `./gradlew dbfit-java:mysql:integrationTest` both run through fine. :+1:

**Comment by javornikolov** [comment]
Awesome! What about postgresql - is it still working fine?

**Comment by MMatten** [comment]
>Awesome! What about postgresql - is it still working fine?

`./gradlew dbfit-java:postgres:integrationTest`  runs too.

**Comment by MMatten** [comment]
Could any other integration tests need running?

**Comment by javornikolov** [comment]
Nice :-) I think all the rest is not affected so it's supposed to still be fine. Thanks a lot for the check! Merging...

**Pull request merged**
