### PR TITLE
Configure guest VM firewall for host access to FitNesse server

### PR DESCRIPTION
**Pull request by MMatten**
Allow access to VM TCP port 8085 for host browser access to FitNesse.

### CODE REVIEW

**Comment by MMatten** [comment]
Resolves #425.

**Comment by javornikolov** [comment]
@MMatten, I guess some actions should be invoked from the imported cookbook?

**Comment by MMatten** [comment]
>@MMatten, I guess some actions should be invoked from the imported cookbook?

Ah, indeed! I've omitted to commit the `firewalld.rb` recipe to configure the firewall! Will add now.

**Comment by MMatten** [comment]
Now with added recipe.

**Comment by javornikolov** [comment]
Looks good now :+1:

**Pull request merged**
