### PR TITLE
sqlserver test dependency on mssql jdbc driver

### PR DESCRIPTION
**Pull request by javornikolov**
build: declare sqlserver dependency on mssql jdbc driver

### CODE REVIEW

**Comment by javornikolov** [comment]
This is to address a point raised in #365
@MMatten, can you test?

**Comment by MMatten** [comment]
Great. I test this out.

**Comment by MMatten** [comment]
Working well. :thumbsup:

**Comment by MMatten** [comment]
It's not actually a dependency for the `compileJava` or `integrationTestCompileJava` stages but it does provide the dependency for both the `test` and the `integrationTest` tasks.

It is better to list it as a `testRuntime` and `integrationTestRuntime` dependency?

**Comment by javornikolov** [comment]
Is it for both `test` and `integration` or just for integration? Anyway - already merged into master. I think we can rebase #365 and specify the more precise dependency there.

**Comment by MMatten** [comment]
We need the driver for both sets of tests.

**Comment by javornikolov** [comment]
Yes, I just looked and observed the same - doesn't really connect or use the driver, just loading it. OK.

**Pull request merged**
