### PR TITLE
Bump up Gradle to 3.2.1

### PR DESCRIPTION
**Pull request by javornikolov**
* Update Gradle to version 3.2.1
* Refactor the already deprecated `<<` shortcut task definition to `doLast` syntax

### CODE REVIEW

**Comment by MMatten** [comment]
I guess it would make sense to run the `integrationBuild` task to make sure all's well.

**Comment by javornikolov** [comment]
> I guess it would make sense to run the integrationBuild task to make sure all's well.

Yes

**Comment by MMatten** [comment]
I've run `integrationBuild` successfullly with `excludeIntegrationTests=db2,informix,netezza,oracle,sqlserver,teradata`.

**Comment by javornikolov** [comment]
Great. Thank you, @MMatten!
Merging...

**Pull request merged**
