### PR TITLE
Bump up FitNesse to 20210606

### PR DESCRIPTION
**Pull request by MMatten**
Bump up FitNesse to v20210606.

Tested with `./gradlew fastbuild` only.

### CODE REVIEW

**Comment by MMatten** [comment]
@javornikolov do you know if this project has been detached from TravisCI now? I don't see any PR builds.

**Comment by javornikolov** [comment]
> @javornikolov do you know if this project has been detached from TravisCI now? I don't see any PR builds.

I don't know. We had some caveats earlier this year - so we migrated some configuration (was related to Travis moving from Travis.org to Travis.com).
Jake shared positive experience with Github Actions - which might be a good alternative to migrate to (as it might be easier to integrate and with github and to maintain).

**Comment by javornikolov** [comment]
Fitness bump seems ok to me

**Comment by MMatten** [comment]
There's one issue here. There's actually a later version that I should bump to. Let me create a new PR!

**Pull request closed without merging**
