### PR TITLE
Update FitNesse to 20151230

### PR DESCRIPTION
**Pull request by javornikolov**

### CODE REVIEW

**Comment by javornikolov** [comment]
@MMatten , would you be able to test that on the full list of databases? (My environment is a bit limited and I can check the in-memory ones only now).

**Comment by MMatten** [comment]
> @MMatten , would you be able to test that on the full list of databases? (My environment is a bit limited and I can only check the embedded ones now).

Certainly. I do it now.

**Comment by MMatten** [comment]
I've run an `integrationBuild` over all of the DB types - success.

**Comment by javornikolov** [comment]
Perfect. Thanks for checking!

**Pull request merged**
