### PR TITLE
Release 4.0.0

### PR DESCRIPTION
**Pull request by javornikolov**
Release 4.0.0

TODO: prepare release notes

### CODE REVIEW

**Comment by MMatten** [comment]
@javornikolov exciting stuff. Need help with any of the release bits?

**Comment by javornikolov** [comment]
Hi @MMatten, thanks a lot for offering your help! I was about to ask you yesterday but I fell asleep :-)

There are two things in my mind which I think it's good to do:
* Some testing that things work OK;
* Understand should we do anything about #490

**Comment by MMatten** [comment]
Yes. #490 has been at the back of my mind for a while. I think I can find some time to fix it, maybe this weekend. I think I even have a draft of the code in a local repo somewhere. 

About general testing. I can run all of the acceptance tests again with a build from 'master'. Do you think we need to do anything else?

**Comment by javornikolov** [comment]
Yes, running acceptance tests across environments of interest would be of great help. You may rather pick branch `release/4.0.0` instead of master fot the testing.

Unless #490 is a strong regression - we may even decide to postpone it for the next release. There was a request for issuing a new release soon. We can do another minor release a bit later.

**Comment by MMatten** [comment]
It looks like we have an issue with the Vagrant VM provisioning. It's failing on the SQL Server installation at the moment. Perhaps the installer has been updated and any response file no longer matches the questions. I'll take a closer look at the end of the week.

**Comment by MMatten** [comment]
During Vagrant provisioning I'm seeing a warning about the Postgres config.

```==> default: Recipe: dbfit_test::postgres
==> default:   * postgresql_database[dbfit] action create
==> default: The PGconn, PGresult, and PGError constants are deprecated, and will be
==> default: removed as of version 1.0.
==> default: 
==> default: You should use PG::Connection, PG::Result, and PG::Error instead, respectively.
==> default: 
==> default: Called from /var/chef/cache/cookbooks/database/libraries/provider_database_postgresql.rb:132:in `db'
```
Shall we peal off another PR or wait until this becomes fatal at some point in the future?

**Comment by javornikolov** [comment]
As far as I understand that only affects the test VM provisioning and not the dbfit product itself. We can peel off an issue but as soon as it's still working I woud vote for focusing on the dbfit release. We can address the technical debt later.

**Comment by MMatten** [comment]
I'm currently seeing SQL Server tests fail (flow mode and standalone) when run via Gradle, but not via the FitNesse UI. I'll spend a little more time trying to work out what's going on. I'm seeing messages like this:-

image

**Comment by MMatten** [comment]
I wonder if this is related to this observation too:-

```
~/dbfit3/dbfit$ ./gradlew eclipse
Starting a Gradle Daemon (subsequent builds will be faster)

> Task :dbfit-java:eclipseClasspath 
Could not resolve: org.fitnesse:fitnesse:20161106
Could not resolve: org.reflections:reflections:0.9.10
Could not resolve: commons-codec:commons-codec:1.10
Could not resolve: org.apache.commons:commons-lang3:3.4
Could not resolve: com.github.dbfit:fitlibrary:20091020
Could not resolve: commons-io:commons-io:2.4
Could not resolve: mysql:mysql-connector-java:5.1.36
Could not resolve: org.postgresql:postgresql:42.0.0.jre7
Could not resolve: org.hsqldb:hsqldb:2.3.3
```

**Comment by javornikolov** [comment]
I've never used `eclipse` target but it really seems strange that it cannot resolve the dependencies...

**Comment by javornikolov** [comment]
Rebased after merging #610

**Comment by MMatten** [comment]
It's surprising. It always worked well before in previous Gradle versions.

It does have a reputation of being less than perfect it seems. E.g.
https://stackoverflow.com/questions/31126415/eclipse-and-gradle-classpath-out-of-sync-cannot-be-resolved-to-a-type

**Comment by MMatten** [comment]
@javornikolov regarding the SQL Server test failures when run from Gradle, I'm not really sure what's going on here. It will obviously affect the usability of the product though for anyone who will running their tests via Gradle.

Any ideas?

**Comment by MMatten** [comment]
For the SQL Server test failures I can only think that for some reason the Stand-alone mode tests are now running before the flow mode ones and that lack of a
```
|dbfit.util.Export|
|dbfit.fixture|
```
after the last stand-alone mode test means that the flow mode tests fail.
I'll create another PR to add this.

**Comment by MMatten** [comment]
Added #614.

**Comment by MMatten** [comment]
@javornikolov All tests are currently passing. Can we merge those other PRs in before the release?

**Comment by javornikolov** [comment]
@MMatten, sorry for leaving you to fight with that alone! It's awesome that you managed to sort it out!

I just merged the other branches and rebased the release branch here.

**Comment by MMatten** [comment]
@javornikolov Best wishes to you and your family for a very merry Christmas and a wonderful new year! As usual it's been great working with you again. Best regards, Mark.

**Comment by javornikolov** [comment]
Thank you @MMatten! Merry Christmas to you too! Let you have much health, joy and happiness in the new year!

**Comment by MMatten** [comment]
Howdy partner. Is there anything I can help with to move this on?

**Comment by javornikolov** [comment]
Hi Mark. Thanks for your ping here! I think we're in good shape to ship that, we just need to prepare some release notes based on the changes since the previous release - there are some helper scripts as per the description in `releasing` folder. Other than that I think it's all good enough.

I'm in the middle of a terrible flue (actually I hope I've already passed the worst of it). Hopefully soon I'll be in shape to stitch the final bits to publish this release.

**Comment by MMatten** [comment]
Oh no. I'll see if I can work out what to do with those scripts.

Well, get well soon! I've never had flu but I hear it's not nice. All the best. Talk soon.

**Comment by javornikolov** [comment]
BTW, there is a new FitNesse version released: https://bintray.com/fitnesse/release/fitnesse. It might worth squweezing it in the current DbFit release in case it works just fine out of the box.

**Comment by MMatten** [comment]
> BTW, there is a new FitNesse version released: https://bintray.com/fitnesse/release/fitnesse. It might worth squweezing it in the current DbFit release in case it works just fine out of the box.

OK. I can run all of the tests again with it over the next day or two.

**Comment by javornikolov** [comment]
>> BTW, there is a new FitNesse version released: https://bintray.com/fitnesse/release/fitnesse. It might worth squweezing it in the current DbFit release in case it works just fine out of the box.
> 
> OK. I can run all of the tests again with it over the next day or two.

Great, thank you! I already merged that into master and rebased the release branch here. At first glimpse it works OK.

I'm currently reviewing old merged PRs to update their milestone and possibly other bits: which is needed to generate the release notes.

**Comment by MMatten** [comment]
I've started to rerun all the tests but a few issues creating a Vagrant VM as the SQL Server installer appears to be broken:-

https://social.technet.microsoft.com/Forums/windows/en-US/037af9f4-665d-44ae-baea-45edb166b05a/evaqluation-period-expired-while-trying-to-install-ms-sql-server-on-ubuntu?forum=sqlexpress&prof=required

I'll carry on with some other bits.

(There's also a forum request for a fix to the Netezza adapter parameters. Should be include this in v4.0.0?)

**Comment by MMatten** [comment]
@javornikolov I'm currently working to resolve #490 via an enhancement (in https://github.com/dbfit/dbfit/tree/ExecuteProcedureExpectException-global-support).

I'll raise the PR asap for review.

**Comment by andreasmarkussen** [comment]
Is it possible to download the 4.0 version for test spin?

**Comment by MMatten** [comment]
@andreasmarkussen are you able to access the build artefact at https://s3.amazonaws.com/dbfit/artifacts/dbfit/dbfit/2918/2918.1/dbfit-complete-4.0.0.zip?

**Comment by andreasmarkussen** [comment]
@MMatten Yes! I am able to download it! Trying it out during my workday tomorrow.

**Comment by muirio** [comment]
Hi folks. I love DbFIt, it's great. Do you mind me asking if you found any time to finish v4.0.0? I don't know if there are any changes to be expected to the preview build posted a couple of comments up by Mark last year.

**Comment by muirio** [comment]
Hi @javornikolov , @MMatten. I love DbFIt, it's great! Do you mind me asking if you found any time to finish v4.0.0? I don't know if there are any changes to be expected to the preview build posted a couple of comments up by Mark last year.

**Comment by bhuesemann** [comment]
@javornikolov @MMatten I've implemented a beta version of Bigquery driver (and also implemented a Hana driver in past). Currently I'm working on this branch, with openjdk version "13.0.1" and gradle 6.0.1. It compiles well (fixed some deprecation errors) but needs more testing. Anything I should take a look at while I'm doing so?

**Comment by IOudo** [comment]
Hi,
Is there a chance that the release 4.0 be available or the subject is postponed ?
We actually look for this version to conserve compatibility with the last version of fitnesse ( issue  #605 )

Thank you for your work, 

Best regards,

**Comment by bhuesemann** [comment]
I'm actively using dbFit in some of our projects and I can contribute what I have, but it needs extensive testing. I've also updated to more recent client versions of MS SQLServer/Azure SQL and Oracle. Also the testvm build process needed some updates to reflect those updates. I think along with the already existing changes on the branch this is worthy a major update but the changes should be reviewed by @javornikolov or @MMatten and need extensive testing.

**Comment by bhuesemann** [comment]
I've updated and fixed the test-vm and successfully retested sqlserver, db2, oracle, derby, hsql, mysql and postgresql.

Currently following databases are verified and supported in my fork:
DB2 Express-C 11.1.4.4
Oracle Database 11g Express Edition Release 11.2.0.2.0 - 64bit Production (will update at a later time)
Postgres: 9.6 (will update at a later time)
MySQL 5.7.31 Community Edition (will update and add MariaDB at a later time)
Microsoft SQL Server 2017 (RTM-CU21) (KB4557397) - 14.0.3335.7 (X64) 

Currently unverified in my fork of 4.0 but supported in earlier versions:
- Informix (will try to test informix iif.12.10.FC12IE)
- Teradata (will not test it as long as I don't have a need)

Beta support (added by me):
- Google BigQuery
- SAP HANA

Planned (on my personal roadmap)
- Exasol
- Azure SQL DB (might already work with the existing ms sqlserver implementation and updated client libs)
- Azure Synapse (might already work with the existing ms sqlserver implementation and updated client libs)
- Snowflake

Additional features / tools I aim to release at a later time (they exist already)
- Tool DBFitBot that loads testresults into a database table + email notification when regression testing failed
- Azure Devops support (converting testresults into junit xml format)

@javornikolov or @MMatten 
Will you work on pull requests with me? I'm willing to contribute everything I have.

**Comment by javornikolov** [comment]
Thank you, @bhuesemann! I am willing to dedicate some time to move dbfit forward. I envision we 1st finalize dbfit 4.0 as a baseline and then we may issue other release with more new features.

**Comment by bhuesemann** [comment]
@javornikolov Sounds great. So I'll make a clean new fork and commit all changes I consider helpful to get the baseline on this branch. It will need some hours clearing out all changes I've already integrated for Bigquery and Hana, but this should only affect the gradle build and the test-vm.
I did some changes due to updating to Gradle 6, Openjdk 13 (code changes) and getting the test-vm ready to run on centos7 and compatible to current chef cookbooks (some are deprecated meanwhile) and more recent db versions. So this will be the first part of our work. Then we will go ahead with feature branches. @MMatten was also active on some branches and it would be great to merge as far as possible and clear out branches not needed anymore. Expect a PR in the next days.

**Comment by bhuesemann** [comment]
This is the PR #649

**Comment by MMatten** [comment]
Hi @javornikolov. How do you think we should move this one? Perhaps we should release ASAP and the evolve from there. Any thoughts?

**Comment by javornikolov** [comment]
> Hi @javornikolov. How do you think we should move this one? Perhaps we should release ASAP and the evolve from there. Any thoughts?

@MMatten, yes - no need to add more features for this release. We need to resolve the issue with publishing to maven repo - we have a github issue for that. The old approach is broken with the newer Gradle that we have now.

**Comment by MMatten** [comment]
> we have a github issue for that

Can you point me at it and I'll take a look?

**Comment by javornikolov** [comment]
> > we have a github issue for that
> 
> Can you point me at it and I'll take a look?

Hmm, I cannot find it... Maybe it has been just in my head :-) Anyway - the plugin for publishing to maven got obsolete, deprecated. It might have been with our current gradle or more recent one - I don't remember exactly.

**Comment by MMatten** [comment]
> Hmm, I cannot find it... Maybe it has been just in my head :-) Anyway - the plugin for publishing to maven got obsolete, deprecated. It might have been with our current gradle or more recent one - I don't remember exactly.

I can't even remember who had the credentials for the Sonatype Nexus repo - did you publish the last set of JARs? I've had a look around old emails for something but nothing obvious has turned up.

**Comment by MMatten** [comment]
@javornikolov I've checked the JAR publishing and it still seems OK (at least for the Sonatype snapshot repo). As you can see I've uploaded a `4.0.0` snapshot, [here](https://oss.sonatype.org/content/repositories/snapshots/com/github/dbfit/dbfit/4.0.0-SNAPSHOT/).

So, I'm guessing that it probably still works for release versions too.

**Comment by bhuesemann** [comment]
@javornikolov @MMatten Great stuff. If you release this I'll take another go to integrate all the stuff from https://github.com/dbfit/dbfit/pull/649 in the next release with your help.

**Comment by javornikolov** [comment]
Thanks, @MMatten, it's great to know that we're able to still publish artifacts with the current technologies (I guess my issues have been with Gradle 7.x).

@MMatten, @bhuesemann, I believe we are good to release. I intend to tidy-up this branch - for sake of the convention I want to use the same name for the release. I will copy the current one with different name so that we can see what we may use from it for future enhancements.

**Comment by MMatten** [comment]
@javornikolov I see that there's a newer version of FitNesse available now. Should we squeeze that into our release? I can run some tests and create a PR to cover this.

**Comment by MMatten** [comment]
So, I'm trying to sort out the Snowflake test failures when bring in the `CoreTests` and it seems that Snowflake doesn't support stored procedures with OUT parameter types so I'm looking at a re-org on the CoreTests to move out `CalcLength` and include it into all the adapters that support this (e.g. via `!include` or a symlink in the test suite).

Also Snowflake (like SQL Server, at least) supports stored procedures with a RETURN clause so I'd like to cover this with a test but the `StatementExecution` and (probably more so) `StatementExectionReturningResultSet` might need some changes as "having a return value" seems to equate to "is a function" and so we're generating invalid statements (e.g. `{ ? = myproc(1, 2) }` where `myproc` is actually a stored proc, not a function.

@javornikolov Any pointers here would be useful so we can drag this thing over the line.

**Comment by javornikolov** [comment]
@MMatten, I need to get deeper to figure out what kind of stored procs are these...

If a stored proc has a return value... what is the way to invoke it if it is not like a function call?

**Comment by MMatten** [comment]
> @MMatten, I need to get deeper to figure out what kind of stored procs are these...
>
>If a stored proc has a return value... what is the way to invoke it if it is not like a function call?

With Snowflake, stored proc return values are accessed via a result set, as far as I can tell, There is a discussion here:
https://community.snowflake.com/s/question/0D53r00009qnAG8CAM/how-to-assign-the-result-of-a-stored-procedure-call-to-a-variable

In this example the stored proc's return value is accessed by another (Javascript-based) stored proc. It seems to be very JDBC-like (and perhaps it's exactly that). I don't think it's possible to access the return value using a stored proc written in SQL in Snowflake.

For SQL Server, things are easy in T-SQL. E.g.: -
```
SELECT @returnVal = dbo.MyStoredProc(765);
```

**Comment by javornikolov** [comment]
Hi @MMatten, I rebased this branch using `main`. I saved the previous branch as `topic/branch_4.0.0_leftovers` (in case there is anything important there).

I propose that we release this version and we can handle the core tests refactoring later. Snowflake is new addition and we can declare it kind of experimental at the moment with the caveats of its core tests status. In terms of sorting it out in longer term - my toughts are in direction of introducing some kind of abstraction so that we can plug-in different strategies of execution of `function-like` things (either via ? = call; via result set; or possibly some other way).

**Comment by MMatten** [comment]
That sounds good to me!

There are a lot of JUnit depreciation warnings coming out of the build. Do we fix or leave?

**Comment by javornikolov** [comment]
I suggest to rather leave JUnit as is for now and later upgrade to JUnit 5 which will anyway need changes.

**Comment by MMatten** [comment]
OK. Again, makes sense. Great, so we're good to roll this out.

**Comment by MMatten** [comment]
Hi @javornikolov, I'm not sure where we left this now. Are you going to be making some moves on this, or need others do some bits?

**Comment by javornikolov** [comment]
Hi @MMatten, I prepared and merged the release on Github (release notes need some refinement).

I also ran ./gradlew uploadArchives, yet I am not quite sure whether it got uploaded to sonatype maven repo... - I cannot see the new version there.

**Comment by MMatten** [comment]
>> I also ran ./gradlew uploadArchives, yet I am not quite sure whether it got uploaded to sonatype maven repo... - I cannot see the new version there.

Does everything from this page look OK in our project? I think this is the guide I used to set up the gradle config originally:
https://central.sonatype.org/publish/publish-gradle/#signing-artifacts

**Comment by MMatten** [comment]
@javornikolov the last 4.0.0-SNAPSHOT version I can see is from March this year.

**Comment by MMatten** [comment]
@javornikolov any log messages we can use to diagnose this?

**Comment by javornikolov** [comment]
> @javornikolov any log messages we can use to diagnose this?

@MMatten, nothing specific appeared in the Gradle output.

**Comment by MMatten** [comment]
@javornikolov if you can find a way to share the Sonatype repo credentials with me I can try to diagnose the issue.

**Comment by MMatten** [comment]
@javornikolov otherwise I can try to create new credentials - let me know how to proceed please. Thanks.

**Comment by javornikolov** [comment]
> @javornikolov otherwise I can try to create new credentials - let me know how to proceed please. Thanks.

@MMatten, I rather wonder how to grant permissions to you to access and publish to the sonatype repo.

I will open separate issue for this case for sake of easier visibility

**Pull request merged**
