### PR TITLE
Fix postgres symbol tests failure

### LINKED ISSUE #557: CoreTests.CommonSuite.Symbols fails for PostgreSQL
The INSERT into `testtbl` produces and exception:

```
org.postgresql.util.PSQLException: ERROR: column "val" is of type integer but expression is of type character varying
  Hint: You will need to rewrite or cast the expression.
  Position: 44
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2161)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1890)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:559)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:417)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:410)
	at dbfit.fixture.StatementExecution.run(StatementExecution.java:13)
	at dbfit.fixture.DbObjectExecutionFixture.executeStatementAndEvaluateOutputs(DbObjectExecutionFixture.java:184)
	at dbfit.fixture.DbObjectExecutionFixture.runRow(DbObjectExecutionFixture.java:155)
	at dbfit.fixture.DbObjectExecutionFixture.doRows(DbObjectExecutionFixture.java:79)
	at fit.Fixture.doTable(Fixture.java:156)
	at fitlibrary.traverse.AlienTraverseHandler.doTable(AlienTraverseHandler.java:21)
	at fitlibrary.traverse.workflow.DoTraverseInterpreter.interpretWholeTable(DoTraverseInterpreter.java:104)
	at fitlibrary.traverse.workflow.DoTraverseInterpreter.interpretWholeTable(DoTraverseInterpreter.java:89)
	at fitlibrary.DoFixture.interpretWholeTable(DoFixture.java:73)
	at fitlibrary.suite.InFlowPageRunner.run(InFlowPageRunner.java:27)
	at fitlibrary.DoFixture.interpretTables(DoFixture.java:42)
	at dbfit.DatabaseTest.interpretTables(DatabaseTest.java:26)
	at fit.Fixture.doTables(Fixture.java:81)
	at fit.FitServer.process(FitServer.java:81)
	at fit.FitServer.run(FitServer.java:56)
	at fit.FitServer.main(FitServer.java:41)
```

### PR DESCRIPTION
**Pull request by javornikolov**
* Unify Multipy function across environments, use MultiplyIO name where an inout parameter has been used
* Unify CalcLength function so that it can be reused across acceptance tests of all environments
* Add support for PostgreSQL `OUT` and `INOUT` parameters
* Fix Symbols acceptance tests incompatibility with PostgreSQL (always use a String parameter for CalcLength parameter otherwise PostgreSQL fails since it doesn't try to do an implicit conversion)
* Bump up PostgreSQL jdbc driver version

resolves #557 together with #562

### CODE REVIEW

**Comment by MMatten** [comment]
In the commit message, I didn't really understand
>  the usual output parameters are not really currently supported for postgres.
What is lacking for Postgres?

**Comment by javornikolov** [comment]
PostgreSQL demands if there is an output parameter:
 - the function return type is mandatory and it must match the type of the output parameter
 - if there are multiple output parameters, the return type should be a record

Essentially - seems that PostgreSQL always returns output parameters as a function return value. I'm not sure if there are alternative ways for retrieving them. What we currently support in DbFit is function/procedure argments of INPUT type only. (E.g. we cannot have a named output parameter which was the trouble with the initial Symbols test).

**Comment by javornikolov** [comment]
Currently there is some trouble with DB2. I don't know what's wrong with it - no obvious mistakes at first glimpse.

**Comment by MMatten** [comment]
> Essentially - seems that PostgreSQL always returns output parameters as a function return value. I'm not sure if there are alternative ways for retrieving them. What we currently support in DbFit is function/procedure argments of INPUT type only. (E.g. we cannot have a named output parameter which was the trouble with the initial Symbols test).

For Postgres could we could retrieve the `OUT` parameter values using a `StatementExecutionCapturingResultSetValue`?

**Comment by MMatten** [comment]
Can we somehow upload (e.g. to the AWS S3 area) the test reports during the builds so we could see that is in
 
> There were failing tests. See the report at: file:///home/travis/build/dbfit/dbfit/dbfit-java/db2/build/reports/tests/integrationTest/index.html

**Comment by MMatten** [comment]
Otherwise I can install DB2 again on my vagrant VM and run the tests via the UI.

**Comment by javornikolov** [comment]
I managed to run the UI tests through docker (seems quicker to fire it up compared to Vagrant). But the error message is quite cryptic: `db2 SQL Error: SQLCODE=-440, SQLSTATE=42884` - I think while trying to set a Multiply parameter (via setObject).

**Comment by MMatten** [comment]
What is the current schema when you call the proc?

http://stackoverflow.com/questions/18367803/db2-java-stored-procedure-call-return-error-sqlcode-440-sqlstate-42884

**Comment by javornikolov** [comment]
!|Connect|localhost:50000|DFTEST|DFTEST|DBFIT|

**Comment by MMatten** [comment]
Can you log into DB2 and check that the proc exists?

http://stackoverflow.com/questions/15600755/db2-list-of-stored-procedure-in-a-database

**Comment by MMatten** [comment]
I'm not sure, perhaps you need to include more clauses (as in the example below) to ensure that it gets created as a SQL, rather C/Java external function?
```
    CREATE FUNCTION TAN (X DOUBLE)
      RETURNS DOUBLE
      LANGUAGE SQL
      CONTAINS SQL
      NO EXTERNAL ACTION
      DETERMINISTIC
      RETURN SIN(X)/COS(X);
```

**Comment by javornikolov** [comment]
``` sql
select procname from syscat.procedures where procschema = 'DFTEST'

PROCNAME                                                                                                                        
------------------
CALCLENGTH                                                                                                                      
CONCATENATESTRINGS                                                                                                              
MAKEUSER                                                                                                                        
MULTIPLYIO
```

The other function which I used as example (ConcatenateF) is also not there.

**Comment by javornikolov** [comment]
Looks like functions and procedures in DB2 is quite different. I can use the function from sql query but not in a call:
``` sql
db2 => call multiply(2, 3)
call multiply(2, 3)
SQL0440N  No authorized routine named "MULTIPLY" of type "PROCEDURE" having 
compatible arguments was found.  SQLSTATE=42884

db2 => SELECT multiply(3, 2) FROM SYSIBM.SYSDUMMY1
SELECT multiply(3, 2) FROM SYSIBM.SYSDUMMY1

1          
-----------
          6

  1 record(s) selected.
```

**Comment by javornikolov** [comment]
http://www.dbforums.com/showthread.php?1631503-how-can-i-call-a-simple-sql-pl-defined-function-using-jdbc

**Comment by MMatten** [comment]
So it looks like we could just form a different statement text and retrieve the return value from the 'ResultSet`.

**Comment by javornikolov** [comment]
> So it looks like we could just form a different statement text (a query instead of a CALL) and retrieve the return value from the ResultSet (hopefully using StatementExecutionCapturingResultSetValue as it currently is).

It seems too exotic to try calling DB2 functions explicitly (I'm not even sure whether it's possible to extract their metadata with list of parameters).

On the other hand PostgreSQL seems to allow calling procedures with output parameters in the standard way (in addition to calling it as function). So I'm rather looking into adding support for that postgres output parameters. Some preparation committed to b8430d5 (perhaps its worth a separate PR).

**Comment by MMatten** [comment]
> (I'm not even sure whether it's possible to extract their metadata with list of parameters).

Perhaps via JDBC methods rather than DB metadata.

**Comment by MMatten** [comment]
> It seems too exotic to try calling DB2 functions explicitly

Maybe using something like: 

`SELECT F(1,2) FROM SYSIBM.SYSDUMMY1` and then reading the resell set.

**Comment by javornikolov** [comment]
> SELECT F(1,2) FROM SYSIBM.SYSDUMMY1 and then reading the resell set.

Yes, I got your idea from before. It needs some research to figure out in which order to pass the parameters - we may try to deal with DB2 separately. I would vote for PostgreSQL here - as it looks easier to implement and harder to workaround the current gap with it in case of multiple output params. (For DB2 the function may be wrapped in a SQL and tested within `Query`).

**Comment by javornikolov** [comment]
@MMatten, would you be able to check if that works on the Vagrant test VM for the databases outside Travis build? I touched some stored procs e.g. in Informix which I haven't tested.

I managed to add support for PostgreSQL output parameters here (it was possible without passing the list of arguments to getAllProcedure parameters - so I removed that change). With that we get the common symbols test pass throughout all environments.

**Comment by MMatten** [comment]
@yavornikolov yes, certainly. It will take me a couple of days to get to it though. I'll take a look at the whole PR again too.

**Comment by MMatten** [comment]
I think we have a new vagrant/Chef issue #568.

**Comment by MMatten** [comment]
After removing `Berksfile.lock` I then observe: -

```
==> default: ================================================================================
==> default: Recipe Compile Error in /var/chef/cache/cookbooks/dbfit_test/recipes/default.rb
==> default: ================================================================================
==> default: 
==> default: NoMethodError
==> default: -------------
==> default: undefined method `client_version' for Custom resource mysql2_chef_gem_mysql2_chef_gem_mysql from cookbook mysql2_chef_gem
==> default: 
==> default: Cookbook Trace:
==> default: ---------------
==> default:   /var/chef/cache/cookbooks/dbfit_test/recipes/mysql.rb:5:in `block in from_file'
==> default:   /var/chef/cache/cookbooks/dbfit_test/recipes/mysql.rb:3:in `from_file'
==> default:   /var/chef/cache/cookbooks/dbfit_test/recipes/default.rb:6:in `from_file'
==> default: 
==> default: Relevant File Content:
==> default: ----------------------
==> default: /var/chef/cache/cookbooks/dbfit_test/recipes/mysql.rb:
==> default: 
==> default:   1:  include_recipe 'yum-mysql-community::mysql57'
==> default:   2:  
==> default:   3:  mysql2_chef_gem 'default' do
==> default:   4:    gem_version '0.4.5'
==> default:   5>>   client_version node['mysql']['version'] if node['mysql']
==> default:   6:    action :install
==> default:   7:  end
==> default:   8:  
==> default:   9:  mysql_connection_info = {:host => "127.0.0.1",
==> default:  10:                           :username => 'root',
==> default:  11:                           :password => node['mysql']['server_root_password']}
==> default:  12:  
==> default:  13:  users = {"dftest" => "dftest", "dbfit_user" => "password"}
==> default:  14:  
==> default: 
==> default: System Info:
==> default: ------------
==> default: chef_version=13.0.118
==> default: platform=centos
==> default: platform_version=7.3.1611
==> default: ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
==> default: program_name=chef-solo worker: ppid=4826;start=07:54:40;
==> default: executable=/opt/chef/bin/chef-solo
==> default: 
==> default: 
==> default: Running handlers:
==> default: [2017-04-22T07:54:49+00:00] ERROR: Running exception handlers
==> default: Running handlers complete
==> default: [2017-04-22T07:54:49+00:00] ERROR: Exception handlers complete
==> default: Chef Client failed. 0 resources updated in 08 seconds
==> default: [2017-04-22T07:54:49+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2017-04-22T07:54:49+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
==> default: [2017-04-22T07:54:49+00:00] ERROR: undefined method `client_version' for Custom resource mysql2_chef_gem_mysql2_chef_gem_mysql from cookbook mysql2_chef_gem
==> default: [2017-04-22T07:54:49+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```

**Comment by MMatten** [comment]
I'll rebase locally onto #569 and continue testing.

**Comment by javornikolov** [comment]
> I'll rebase locally onto #569 and continue testing.

I just rebased it here in-place.

**Comment by MMatten** [comment]
Testing is now blocked by #571

**Comment by MMatten** [comment]
We have failing Informix tests (the new proc based test): -

image

**Comment by javornikolov** [comment]
> We have failing Informix tests (the new proc based test)

How does it behave with the `master` branch?

**Comment by javornikolov** [comment]
The Informix error is supposed to be addressed by #574

**Comment by MMatten** [comment]
> How does it behave with the master branch?

Failure on `CoreTests.CommonSuite.Symbols`.

**Comment by javornikolov** [comment]
Just rebased on top of master so I hope everything should be OK now.

**Comment by MMatten** [comment]
OK. I'll rebuild a dev VM and run it all through.

**Comment by MMatten** [comment]
Looking good so far. I've still got to test with Teradata, Netezza and SQL Server though.

**Comment by MMatten** [comment]
@javornikolov I'm still having a bit of a nightmare with testing on Windows 10 (it's awful and it's blue screening on me) when trying to build the VM. Will get back to you as soon as.

**Comment by MMatten** [comment]
Teradata tests are passing.

Netezza has been a massive pain to get the emulator running. I've moved on to the 7.2 version. This can run on Linux under VMWare. I need to somehow upload the 7.2 driver though. What's the best way to get this to you? Commit it?

**Comment by javornikolov** [comment]
> What's the best way to get this to you? Commit it?

Not a good idea to "pollute" the repo with a large binary jar. If it's hard to get the driver directly from IBM site, any file sharing should be fine (gdrive, dropbox, expirebox,...). You may share some hashsum here to ensure the file has been transferred intact.

**Comment by javornikolov** [comment]
I forgot to mention - for local testing you may just copy jdbc drivers to `custom_libs` folder.

**Comment by MMatten** [comment]
>> What's the best way to get this to you? Commit it?

> Not a good idea to "pollute" the repo with a large binary jar. If it's hard to get the driver directly from IBM site, any file sharing should be fine (gdrive, dropbox, expirebox,...). You may share some hashsum here to ensure the file has been transferred intact.

I've just shared the driver file with you. We'll need to rename it and update the grade build.

**Comment by MMatten** [comment]
Also, it looks like Netezza doesn't support named proc params or output params.

**Comment by MMatten** [comment]
I think it's PostgreSQL based. It can return a single value (scalar or a (single column) table of values).

**Comment by javornikolov** [comment]
> I've just shared the driver file with you. We'll need to rename it and update the grade build.

Thank you @MMatten!  I've just uploaded the file, sha-1:
```
d89e4e54280b1ef0747346bba6799fbd064a3645 *nzjdbc3-7.2.jar
```

**Comment by MMatten** [comment]
> d89e4e54280b1ef0747346bba6799fbd064a3645

That hash is correct. :+1:

**Comment by javornikolov** [comment]
> Also, it looks like Netezza doesn't support named proc params or output params.

Any ideas how to overcome that?

**Comment by javornikolov** [comment]
Perhaps the issue with Netezza stored procs in symbols tests is already in master. If everything else seems OK, maybe we rather merge the current PR (named after postgresql) and take care about Netezza separately.

**Comment by MMatten** [comment]
> Perhaps the issue with Netezza stored procs in symbols tests is already in master.

Let me test that.

**Comment by MMatten** [comment]
> Let me test that.

Yes, it looks like we introduced this break in 8d3e2c7537a85e6a4c22cc32a0dfb4a7fd21ed33. I can't remember which DBMSs we tested this on but at least not Netezza.

**Comment by MMatten** [comment]
Note that I still should test this PR with SQL Server too I guess.

**Comment by MMatten** [comment]
All SQL Server tests apart from the know issues in `master` as passing 👍

**Comment by javornikolov** [comment]
> All SQL Server tests apart from the know issues in master as passing

Great :-) So I think we can already merge that to master to finally fix the broken build. What do you think, is there anything else which may need to do before merging?

**Comment by MMatten** [comment]
I think we should merge this one now. 👍 :)

**Comment by javornikolov** [comment]
Nice, I'm merging it... :-) Thanks @MMatten for the thorough testing - it has revealed quite a few things!

**Pull request merged**
