### PR TITLE
Fix and refactor Informix DateTime types lists

### LINKED ISSUE #464: Simplify InformixEnvironment timestampTypes list initialization
Currently timestampTypes list is quite big. Consider simplifying the initialization - e.g. generate the list with some helper function.

### LINKED ISSUE #465: Bad timestamp types list for Informix
In `InformixEnvironment.timestampTypes` list we have `HOUR TO FRACTION(5)` twice and we're missing `MINUTE TO FRACTION(5)`

### PR DESCRIPTION
**Pull request by javornikolov**
resolves #464 resolves #465

### CODE REVIEW

**Comment by javornikolov** [comment]
@MMatten, do DateTime lists look OK to you now? I'm not quite certain what about the `Time` vs `Timestamp` distinction (as I read Informix is quite pedantic and won't like using Timestamp instead of Time).

**Comment by MMatten** [comment]
I can take a look later on but I think we must be missing some acceptance tests too.

**Comment by javornikolov** [comment]
> I think we must be missing some acceptance tests too.

Exactly...

**Comment by MMatten** [comment]
Does this change make it all more cryptic? If we have a unit tests for this then the expected output would be the original format list won't it?

**Comment by MMatten** [comment]
>  I'm not quite certain what about the Time vs Timestamp distinction

I could really have just put them all into a single list. It was just to make the number of `DATETIME <high> TO <low>` list entries more manageable.

**Comment by javornikolov** [comment]
> Does this change make it all more cryptic?

To some extent yes, indeed... Yet - seems easier to check whether the list is correct.

> If we have a unit tests for this then the expected output would be the original format list won't it?

I started with a unit test and that's how I discovered that the original list was wrong! (The fix is in ae5733776d310444d32de9192d0552b6f6f60c83). Looks like it may be good to get that unit test (or reverse version of it) committed - I'll get check it in.

**Comment by javornikolov** [comment]
I extracted hard-coded pre-populated lists of date/time dates into a helper class:
 - allowed adding a unit test (without exposing too much `InformixEnvironment` internals)
 - avoids bloating `InformixEnvironment`
 - neater formatting with one item on line is not a problem

**Comment by MMatten** [comment]
I've revised the acceptance test page for the `DATETIME` types. I can push it to your branch if that's ok?

**Comment by javornikolov** [comment]
> I've revised the acceptance test page for the DATETIME types. I can push it to your branch if that's ok?

Yes, sure - you can go ahead and push your changes here.

**Comment by MMatten** [comment]
Pushed it now. I've reformatted it to make it easier to read (and spot issues).

**Comment by javornikolov** [comment]
Thanks! Looks good to me :+1:. @MMatten, unless you have other ideas for changes here - I'm planning to squash last 3 commits and merge the PR.

**Comment by MMatten** [comment]
Nothing to add. All looking good to me.

**Pull request merged**
