### PR TITLE
Update test vm cookbooks (lvm and others)

### LINKED ISSUE #533: Dev VM: error creating LVM physical volume
Error creating LVM physical volume:

```
==> default:     ================================================================================
==> default:     Error executing action `create` on resource 'lvm_physical_volume[/dev/sdb]'
==> default:     ================================================================================
==> default:     
==> default:     ArgumentError
==> default:     -------------
==> default:     Unable to load lvm attributes [lvs.yaml] for version [2.02.166(2)]. The version/object may not be supported or you may need to upgrade the di-ruby-lvm-attrib gem. Error [No such file or directory @ rb_sysopen - /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/di-ruby-lvm-attrib-0.0.27/lib/lvm/attributes/2.02.166(2)/lvs.yaml]
==> default:     
==> default:     Cookbook Trace:
==> default:     ---------------
==> default:     /var/chef/cache/cookbooks/lvm/libraries/provider_lvm_physical_volume.rb:47:in `new'
==> default:     /var/chef/cache/cookbooks/lvm/libraries/provider_lvm_physical_volume.rb:47:in `action_create'
==> default:     
==> default:     Resource Declaration:
==> default:     ---------------------
==> default:     # In /var/chef/cache/cookbooks/dbfit_test/recipes/diskspace.rb
==> default:     
==> default:       1: lvm_physical_volume '/dev/sdb' do
==> default:       2:   action :create
==> default:       3: end
==> default:       4: 
==> default:     
==> default:     Compiled Resource:
==> default:     ------------------
==> default:     # Declared in /var/chef/cache/cookbooks/dbfit_test/recipes/diskspace.rb:1:in `from_file'
==> default:     
==> default:     lvm_physical_volume("/dev/sdb") do
==> default:       provider Chef::Provider::LvmPhysicalVolume
==> default:       action [:create]
==> default:       retries 0
==> default:       retry_delay 2
==> default:       default_guard_interpreter :default
==> default:       declared_type :lvm_physical_volume
==> default:       cookbook_name "dbfit_test"
==> default:       recipe_name "diskspace"
==> default:     end
```

### PR DESCRIPTION
**Pull request by javornikolov**
Update test vm cookbooks, mostly in order to pick newer lvm version since the existing one is not compatible with the latest vagrant box.

Intended to resolve #533

### CODE REVIEW

**Comment by MMatten** [comment]
Cool. I'll have to test it tomorrow.

**Comment by MMatten** [comment]
Working well :+1:

**Comment by javornikolov** [comment]
> Working well

That's good! Meanwhile newer versions of some other cookbooks have emerged so I refreshed `Berksfile.lock` and pushed it. @MMatten can we test again?

**Comment by MMatten** [comment]
Sure. I'll do it now.

**Comment by MMatten** [comment]
Now something odd's happening. NFS mounting is hanging.

```Dec 23 19:05:58 mark-Dell-System-XPS-L502X systemd[1]: Started NFS server and...
Hint: Some lines were ellipsized, use -l to show in full.
exportfs: duplicated export entries:
exportfs: 	192.168.33.10:/home/mmatten/dbfit3/dbfit
exportfs: 	192.168.33.10:/home/mmatten/dbfit3/dbfit
==> default: Mounting NFS shared folders...
```

**Comment by MMatten** [comment]
I can't think of anything in this PR that's changing that though. I can try rebooting, etc.

**Comment by javornikolov** [comment]
Strange... Could be related to firewall or something. Might worth trying an update of vbox & vagrant?

**Comment by MMatten** [comment]
After a reboot it's working fine.

**Pull request merged**
