### PR TITLE
fix travis setup

### PR DESCRIPTION
**Pull request by javornikolov**
Fix travis CI build

* Downgrade .travis.yml to trusty
* Use https scheme for gradle wrapper

### CODE REVIEW

**Comment by MMatten** [comment]
Hi Javor. It looks like moving from DB2 express to the new docker images is breaking the schema deployment. I can try getting this working on Vagrant VM but I suspect Chef provisioning is going to be broken again. I can create another issue/PR to try to get that working again maybe, if you'll have some time to help get it working again(??).

**Comment by javornikolov** [comment]
Hi @MMatten, I hope you're well in these days of virus infection...

Yes, DB2 on travis is broken now. In fact the existing DB2 and Oracle docker images were already broken yesterday and I started trying to fix them. I succeeded with Orcle one. For the DB2 I tried something but it didn't work out of the box.

Feel free to open another PR. I think I would manage to find a bit more time now.

**Comment by MMatten** [comment]
Hi @javornikolov , good to hear from you and hope all's well with you and yours. I'll fire up my dev machine later this week and start the assessment for the Vagrant setup. Take care. Talk soon.

**Comment by javornikolov** [comment]
@MMatten, I managed to get running db2 and the rest stuff on TravisC2. I touched some db2-related scripts so the instructions and config for the Vagrant VM may also need updating.

**Comment by MMatten** [comment]
Great stuff @javornikolov. Maybe we should make the VM docker-based too. I’m not sure if there are large resource overheads or not though. Any view?

**Comment by javornikolov** [comment]
I had similar toughts too, docker is relatively lightweight and can run inside a VirtualBox VM.

There are other combinations as well - like Vagrant running docker stuff directly (not inside VBox). There might be some limitations though, I haven't tried that yet (e.g. docker was not supported under Windows at some point, later it appeared but I'm not sure about the support of running windows inside docker, etc).

In general at home I tend to have trouble running VBox at the moment. Yet, I managed to bring up the Oracle and DB2 docker boxes (at least one of them at a time).

**Comment by javornikolov** [comment]
I'm merging this PR and we can figure out refinement of the *local environment* setup in a separate one.

**Pull request merged**
