### PR TITLE
Bump up FitNesse to 20161106

### PR DESCRIPTION
**Pull request by javornikolov**

### CODE REVIEW

**Comment by MMatten** [comment]
Something weird happened (the `dbdeploy` patch tracking table seems to be missing on first glance) and I'll need to find out what's going on (will try tomorrow). Error message is: -

```
:dbfit-java:postgres:compileJava UP-TO-DATE
:dbfit-java:postgres:processResources UP-TO-DATE
:dbfit-java:postgres:classes UP-TO-DATE
:dbfit-java:postgres:compileIntegrationTestJava UP-TO-DATE
:dbfit-java:postgres:processIntegrationTestResources UP-TO-DATE
:dbfit-java:postgres:integrationTestClasses UP-TO-DATE
:dbfit-java:postgres:integrationTest
[ant:dbdeploy] dbdeploy 3.0M3
[ant:dbdeploy] Reading change scripts from directory /var/dbfit/dbfit-java/postgres/src/integration-test/resources...
:dbfit-java:postgres:integrationTest FAILED

FAILURE: Build failed with an exception.

* Where:
Build file '/var/dbfit/dbfit-java/build.gradle' line: 96

* What went wrong:
Execution failed for task ':dbfit-java:postgres:integrationTest'.
> com.dbdeploy.exceptions.SchemaVersionTrackingException: Could not retrieve change log from database because: ERROR: relation "changelog" does not exist
    Position: 27

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 22.806 secs
```

**Comment by MMatten** [comment]
Note that this was observed when running the `integrationBuild` task with `gradle.properties` set to:
`excludeIntegrationTests=db2,informix,oracle,netezza,sqlserver,teradata`.

I'd previously successfully run the `fastbuild` task.

**Comment by javornikolov** [comment]
The change tracking table is supposed to be created during test VM provisioning by Chef [test_vm/vendor/cookbooks/dbfit_test/recipes/postgres.rb](https://github.com/dbfit/dbfit/blob/master/test_vm/vendor/cookbooks/dbfit_test/recipes/postgres.rb)

Possibly we messed up something in that recipe.

**Comment by javornikolov** [comment]
@MMatten, maybe #519 would solve the problem with postgres `changelog` table.

**Comment by MMatten** [comment]
I'll rebase this locally onto #518 and test it now.

**Comment by MMatten** [comment]
It's running cleanly with the 4 basic VM DB types (Derby/HSQLDB/MySQL/PostgreSQL). :+1:

**Comment by javornikolov** [comment]
I think that should be enough. We don't use different integration points with FitNesse for the others.

**Comment by javornikolov** [comment]
I'm merging this. Thanks for testing it @MMatten!

**Pull request merged**
