### PR TITLE
Standardise whitespace style

### LINKED ISSUE #320: Non standard whitespace formatting in Teradata*Period*.java
* Tabs used for indentation instead of 4 spaces.
* Whitespace only lines.
* Debugging output (to stdout) present.

### PR DESCRIPTION
**Pull request by MMatten**
Convert tabs to spaces (to resolve #320) and remove stdout debugging output.

### CODE REVIEW

**Comment by MMatten** [comment]
One more tab spotted and now removed.

**Comment by MMatten** [comment]
CI artefact pulls from maven and AWS failed.

**Comment by javornikolov** [comment]
Yes, when you login to Travis CI - a button to re-run tests appears

**Comment by MMatten** [comment]
Thanks for restarting them. I'm not planning on any further commits unless you guys spot something to fix.

**Comment by javornikolov** [comment]
@MMatten, thank you! Looks OK to me.

**Pull request merged**
