### PR TITLE
Enhance HSQLDB stored routine support

### PR DESCRIPTION
**Pull request by MMatten**
Supersedes #553, #541 and #535.

### CODE REVIEW

**Comment by javornikolov** [comment]
@MMatten, that looks good to me :+1:. Unless you have more changes to add - I think we can merge it?

**Comment by MMatten** [comment]
@javornikolov I've nothing else to add.

**Comment by MMatten** [comment]
I'll close down the other PRs.

**Comment by javornikolov** [comment]
> @javornikolov I've nothing else to add.

Cool! I'm merging it then ... Thanks a lot @MMatten !

> I'll close down the other PRs.

In general this can be also done by `closes #nnn` comment in the PR (https://help.github.com/articles/closing-issues-via-commit-messages/). Anyway - not a big deal to do it manually :-)

**Pull request merged**
